#!/usr/bin/python

# OIDs used:
# IGMP-MIB::igmpInterfaceStatus    .1.3.6.1.3.59.1.1.1.1.3
# IGMP-MIB::igmpInterfaceQuerier   .1.3.6.1.3.59.1.1.1.1.5
# IGMP-MIB::igmpMIB                .1.3.6.1.3.59

# Scan function looks not None (aka, IGMP is enabled) in IGMP-MIB::igmpMIB

def inventory_igmp_querier(info):
    inventory = []
    for line in info:
        inventory.append((line[0], None))
    return inventory

def check_igmp_querier(item, _no_params, info):
    for igmpQuerier, querierState in info:
        if item == igmpQuerier:
            querierState = int(querierState)
            if querierState == 1:
                return (0, "OK - Querier state: active")
            else:
                return (2, "CRIT - Querier problem")
    return (3, "UNKNOWN")

check_info["igmp_querier"] = {
    "check_function"        : check_igmp_querier,
    "inventory_function"    : inventory_igmp_querier,
    "service_description"   : "IGMP Querier: ",
    "has_perfdata"          : False,
    "snmp_scan_function"    : lambda oid: oid(".1.3.6.1.3.59.*") != None,
    "snmp_info"		    : ( ".1.3.6.1.3.59.1.1.1.1", [ 5, 3 ] ),
}
